### ISSUE TITLE
Scripts do not work

### ISSUE THREAD

**Issue by nubbix** [davidbombal/red-python-scripts#18]
Code error within

**Comment by davidbombal** [comment]
Which code does not work, and what error are you experiencing?

**Comment by turk0917** [comment]
I also experienced an issue, kinda. I'm brand new to coding so I don't quite understand python. I copied and pasted the code for your Windows10-wifi-email.py. at the end of the code, I changed "email_address" to "email@example.com" in line 59. Then in line number 70, I changed "login_name", "password" to "email2@example.com", "abc123" . When I run the .py app it outputs: Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] on win32
           ^
SyntaxError: invalid syntax

I made a batch (.bat) file to run the code in command prompt (cmd). in the .bat file I wrote this code:
@echo off
"C:\Users\User-name\AppData\Local\Programs\Python\Python39\python.exe" "C:\Users\User-name\3D Objects\Python Apps\wifi-to-email.py"

(I Kept the app in 3d objects because its the only drive that isn't crowded).
Any info helps, -Turk0917
pause
