### ISSUE TITLE
LIne Number 137 Error

### ISSUE THREAD

**Issue by Robin0723** [davidbombal/red-python-scripts#24]
#Error line 137
![Error](https://user-images.githubusercontent.com/88500283/130257852-6321e66a-3eae-459c-93cb-1ff98b411436.png)
Can any one help me with this !!!...

**Comment by Phedevelop** [comment]
Hi @Robin0723 , i had the same error and i found the solution, i guess.

The problem is the "F" inside the print, so if you delete it the problem will be solved.

All the print sentences with the "F" must be changed, my advide just comment the line, copy it and change what i said before.

Let me know if that helps you

**Comment by Phedevelop** [comment]
@Robin0723 remember to run this python script with python3, dont use python 2 because doesnt work on it

**Comment by davidbombal** [comment]
Please use Python 3.6 and greater! Thanks @Phedevelop!
